export default function AboutPage() {
  return (
    <div className="min-h-screen pt-20">
      <div className="px-6 md:px-8 py-12 md:py-20">
        <div className="max-w-2xl mx-auto space-y-16">
          {/* Header */}
          <div>
            <h1 className="text-3xl mb-6">about less</h1>
            <p className="text-lg text-muted leading-relaxed">
              an onchain artwork about what remains when a system keeps taking things away
            </p>
          </div>

          {/* What is less */}
          <section className="space-y-4">
            <h2 className="text-lg">what is less?</h2>
            <p className="text-sm leading-relaxed text-muted">
              less is both a recursive strategy token and an nft collection built on top of it.
              the token continuously consumes itself. the collection records the moments when it does.
            </p>
          </section>

          {/* The recursive token */}
          <section className="space-y-4">
            <h2 className="text-lg">the recursive token</h2>
            <div className="text-sm leading-relaxed text-muted space-y-4">
              <p>
                less is built on a recursive strategy token from strategy protocol.
                every trade on its uniswap pool sends eth into the contract.
              </p>
              <p>
                over time, that eth is used to buy and burn the token itself.
                the supply only moves one way: less.
              </p>
              <p>
                there is no team allocation. no unlock schedule. no inflation.
                just a system that slowly eats itself.
              </p>
            </div>
          </section>

          {/* The collection */}
          <section className="space-y-4">
            <h2 className="text-lg">the collection</h2>
            <div className="text-sm leading-relaxed text-muted space-y-4">
              <p>
                every time the token buys and burns itself, a short mint window opens.
                during that window, each address can mint one piece tied to that specific
                burn event.
              </p>
              <p>
                if nobody mints, the burn still happened onchain—it just leaves no visible
                mark in the collection. these gaps are part of the record.
              </p>
              <p>
                one asset gets smaller. the other accumulates proof that it happened.
              </p>
            </div>
          </section>

          {/* Folding paper */}
          <section className="space-y-4">
            <h2 className="text-lg">folding paper</h2>
            <div className="text-sm leading-relaxed text-muted space-y-4">
              <p>
                visually, each piece is generated by simulating folds on a virtual
                sheet of paper.
              </p>
              <p>
                imagine an 8.5×11 sheet. fold it at the corners again and again.
                each fold leaves an invisible crease. where creases intersect,
                they create compression points.
              </p>
              <p>
                the artwork only shows those points, rendered as a grid:
              </p>
              <div className="font-mono text-base py-4 space-y-1">
                <div><span className="text-muted">░</span> = no intersections</div>
                <div><span>▒</span> = 1 intersection</div>
                <div><span>▓</span> = 2 intersections</div>
                <div><span>█</span> = 3+ intersections</div>
              </div>
              <p>
                each piece is compressed memory. light cells hold little history.
                dense blocks hold lots of overlap.
              </p>
            </div>
          </section>

          {/* The metaphor */}
          <section className="space-y-4">
            <h2 className="text-lg">the metaphor</h2>
            <p className="text-sm leading-relaxed text-muted">
              as the recursive token burns itself down, the less collection grows.
              the folds that led to each piece are invisible—you only see where they collided.
              the system takes away. the art shows what remains.
            </p>
          </section>

          {/* Links */}
          <section className="pt-8 border-t border-border">
            <div className="flex flex-wrap gap-6 text-sm">
              <a
                href="#"
                className="text-muted hover:text-foreground transition-colors"
              >
                contract →
              </a>
              <a
                href="#"
                className="text-muted hover:text-foreground transition-colors"
              >
                strategy protocol →
              </a>
              <a
                href="#"
                className="text-muted hover:text-foreground transition-colors"
              >
                opensea →
              </a>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}
